#!/bin/sh

# to install:
# cp pre-commit .git/hooks
# chmod +x .git/hooks/*
# (но оно типа уже должно само установится)

FILES="$(git diff --cached --name-only --diff-filter=ACM "*.cs")"
[ -z "$FILES" ] && exit 0

dotnet.exe format --files "$(echo "$FILES" | tr '\n' ',')"

echo "$FILES" | tr '\n' '\0' | xargs -0 git add

dotnet.exe build --configuration Release || exit 1
rm -f ParserApp/bin/Release/net45/*.pdb ParserApp/bin/Release/net45/*.exe.config pdfs/Program.zip
cd ParserApp/bin/Release/net45
zip -r ../../../../pdfs/Program.zip ./*
cd ../../../../
git add pdfs/Program.zip

cd LaTeX-documentation
make
cd ..
git add pdfs

exit 0
